"""Add created_at to users

Revision ID: 5fe2731b045c
Revises: 5b85ded723b6
Create Date: 2025-10-03 14:32:21.484957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe2731b045c'
down_revision: Union[str, Sequence[str], None] = '5b85ded723b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_documents_filename'), table_name='documents')
    op.drop_constraint(op.f('documents_owner_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_id_fkey'), 'documents', 'users', ['owner_id'], ['id'])
    op.create_index(op.f('ix_documents_filename'), 'documents', ['filename'], unique=False)
    op.alter_column('documents', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
